### ISSUE TITLE
Add a free software license

### ISSUE THREAD

**Issue by nfitzen** [fosscord/fosscord-client#22]
[CC BY-NC-SA 4.0] is neither a [free software] nor an [Open Source] license, and thus the title of the program (Fosscord) is misleading. Would you consider using a free software license?

[CC BY-NC-SA 4.0]: https://creativecommons.org/licenses/by-nc-sa/4.0/

[free software]: https://www.gnu.org/philosophy/free-sw.html
[Open Source]: https://opensource.org/osd

**Comment by veselcraft** [comment]
this

**Comment by Flam3rboy** [comment]
the problem is that I want a copyleft license that prohibts commercial use of our product as otherwise big corps can just use our work without us profiting from it and our hard work put in

**Comment by Flam3rboy** [comment]
I'll change it to GPL but with no permission for commercial use

**Comment by nfitzen** [comment]
You can't add further restrictions. That's incompatible with the GPL.

> otherwise big corps can just use our work without us profiting from it.

What even is the point of this if people can't distribute copies of Fosscord or charge for certain services freely?

**Comment by Flam3rboy** [comment]
> You can't add further restrictions. That's incompatible with the GPL.
Wrong, I'm allowed to modify it: https://www.gnu.org/licenses/gpl-faq.html#ModifyGPL

> What even is the point of this if people can't distribute copies of Fosscord or charge for certain services freely?
People should be allowed to distribute copies of (or host) Fosscord but only for private non-commercial use.

**Comment by nfitzen** [comment]
@Flam3rboy it wouldn't be the GNU General Public license then; it'd be some other license based on the GPL's legal text. (For incompatibility, see [§ 10](https://www.gnu.org/licenses/gpl-3.0.html#section10).)

Anyway, any interest I had in this project is gone the moment it wasn't free software, so I'm done with this discussion. If it has more legal restrictions than the vanilla Discord client itself (which you can use for business conversations), then I'm not touching it.

Should be called "Proprietarycord" or something.

**Comment by Flam3rboy** [comment]
You are allowed to use Fosscord for business conversations but not make money with the product Fosscord.

**Comment by Flam3rboy** [comment]
Similarly to MongoDB's license that prevents big cloud companies to make money of it

**Comment by nfitzen** [comment]
Whatever, you can do your own thing. Imposing monetary restrictions is absurd.

I just hope people aren't mislead by the name.

**Comment by nfitzen** [comment]
> Similarly to MongoDB's license that prevents big cloud companies to make money of it

MongoDB isn't free software.

**Comment by Flam3rboy** [comment]
> Imposing monetary restrictions is absurd.

Why is that?
We put hard work into this project and shouldn't get componsation? thats sounds like slavery xD

**Comment by nfitzen** [comment]
@Flam3rboy slavery is imposing a ransom on people to be able to use their computer the way they want to. Working on code because you like programming and want to contribute to society is not slavery.

The SSPL only changes § 13 of the AGPLv3 and as such the client-side stuff remains intact, so I don't see your argument here. Server source code isn't as important, but the client source code must remain free.

**Comment by Flam3rboy** [comment]
We want to provide a "open" source alternative to discord that can be expanded by the community and is decentralized, but the Maintainers, should if it ever reaches that point, get a compensation for their work.

**Comment by nfitzen** [comment]
Anyway, as you can tell from me closing this issue, I do not want to get into the free software debate.

If you don't want Proprietarycord to be Open Source/free software, then so be it. Have a nice day, I've stopped caring.

**Comment by Flam3rboy** [comment]
ok it might be possible through donation, but is this conceivable?
I don't think anyone would donate?

**Comment by nfitzen** [comment]
@Flam3rboy like many free software projects, I believe people just like programming amd want to do a social good. Making money can be achieved through charging a fee for server hosting, or through donation, but a project like this shouldn't expect significant monetary gain.

**Comment by nfitzen** [comment]
In terms of technical value, the default Discord client will most likely be superior; I was personally interested because I love free software and want to help contribute to projects in any way I can (which isn't much at the moment).

**Comment by Flam3rboy** [comment]
this might be a viable option: https://opencollective.com/

**Comment by Flam3rboy** [comment]
> In terms of technical value, the default Discord client will most likely be superior

We will implement all the same features with proper theme and secure plugin support on all platforms

**Comment by xNaCly** [comment]
@nfitzen i agree, i personaly want this project to use the gnu license.
@Flam3rboy is the one blocking this advance

**Comment by nfitzen** [comment]
Anyway, regardless of what the server license might be (either AGPLv3, some pushover license, or some proprietary license), the client should most certainly be free software. There is little downside, and the GPL, to my knowledge ensures any plugins will be free software as well.

As for the server license discussion, I think allowing people to charge enough money, and even make a profit from that public service (again, the AGPLv3 ensures they can't impose ridiculous restrictions), should be a thing.
Additionally, for proprietary collaborative projects, we'd require people to sign a CLA, since free software projects generally have multiple copyright holders.

**Comment by DiegoMagdaleno** [comment]
What?

What you are saying is illogical, it would be free and open source not "propietary" what's wrong with the creator of the software not wanting his/her/their product to be sold?, it takes effort and passion to make software and while I am willing to do that for free I don't want random 1 trillion dollar company reusing my software and making money out of it.

The license should block monetizing it, if the creator wants, if you want a free and open source project that allows monetization you are free to go and create your own implementation of Discord and make it follow your terms.

**Comment by nfitzen** [comment]
@DiegoMagdaleno **it's not Open Source if it can't be used or redistributed for any purpose** (so you should change your bio, apparently, since you don't like Open Source).

Anyway, you people are delusional, so whatever.

> what's wrong with the creator of the software not wanting his/her/their product to be sold?

I'll just point to <https://www.gnu.org/pholosophy/shouldbefree.html>, since it takes too much brainpower to argue in favor of Open Source and [free software].

[free software]: https://www.gnu.org/philosophy/free-sw.html

**Comment by DiegoMagdaleno** [comment]
1. Open source means the freedom to read the source code, can I read the FOSScord source code? Yes.
2. Freedom means the freedom to do whatever I want to do with the software, in this case FOSScord isnt free, so it might just be renamed to OSSCord, which sounds dumb.

So explain me again, where in my bio it says I love FREE and open source software, afaik it only says I love Open Source Software?, which FOSScord is?

And I have read the GNU philosophy, and lemme tell you, is the representation of a communist utopia.

**Comment by nfitzen** [comment]
@DiegoMagdaleno see <https://opensource.org/osd>.

**Comment by pbeart** [comment]
If your goal is just to make Discord with slightly fewer features then that's fine, but calling it fosscord is just silly

**Comment by Flam3rboy** [comment]
* with more features

**Comment by Flam3rboy** [comment]
it is open source, but not "free"

**Comment by Flam3rboy** [comment]
rather fair, here you are a I've changed the explanation https://github.com/fosscord/fosscord/wiki

**Comment by Flam3rboy** [comment]
the client is now licensed under the APGL V.3 License

**Comment by Flam3rboy** [comment]
everything is now licensed under GPL V3
except for [fosscord-ui](https://github.com/fosscord/fosscord-ui/issues/27), it is licensed under MIT for e.g. bot dashboards
